spring:
  application:
    name: hw08

  data:
    mongodb:
      database: book_library
      auto-index-creation: true

  shell:
    interactive:
      enabled: true
    command:
      exit:
        enabled: true
      version:
        enabled: false

  logging:
    level:
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG
      org.springframework.data.mongodb.repository.query: DEBUG
      org.mongodb.driver: DEBUG

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.5